from __future__ import annotations

from dataclasses import dataclass

NAVER_SEO_SECTIONS = [
    "상단 요약",
    "이 글에서 바로 답하는 질문",
    "핵심 조건 정리",
    "헷갈리기 쉬운 예외",
    "실전 예시 시나리오",
    "체크리스트",
    "FAQ",
    "마무리 결론",
]

ANGLE_PROMPTS = {
    "판단형": "첫 2문단에서 가능/불가 또는 유리/불리를 명확히 결론내립니다.",
    "비교형": "비슷한 제도나 상황과 비교해 차이를 빠르게 이해시키는 방식으로 씁니다.",
    "실수방지형": "탈락, 부적격, 비용 누락 같은 실수 포인트를 전면에 배치합니다.",
    "체크리스트형": "실행 순서와 점검 항목을 짧고 명확하게 끊어서 씁니다.",
    "사례형": "가상의 독자 사례를 앞세워 판단 흐름을 따라가게 씁니다.",
    "FAQ형": "자주 묻는 질문을 연속 배치해 검색 체류시간을 높이는 방식으로 씁니다.",
}

FAMILY_PRESETS = {
    "기초": {
        "audiences": ["청약초보", "청년 1인 가구", "사회초년생", "무주택 실수요자", "30대 맞벌이", "예비 신혼부부"],
        "intents": ["조건정리", "가능여부", "비교", "실수방지", "체크리스트"],
        "scenarios": ["처음 준비할 때", "세대분리 전", "통장만 있을 때", "기준이 헷갈릴 때", "청약 처음 넣기 전", "무주택 유지 중일 때"],
        "secondaries": ["1순위", "예치금", "세대주", "무주택", "청약홈", "납입횟수", "부양가족수"],
        "priority": 100,
    },
    "특공": {
        "audiences": ["신혼부부", "예비부부", "생애최초 준비자", "다자녀 가구", "노부모 부양 세대", "신생아 특공 준비자"],
        "intents": ["조건정리", "가능여부", "비교", "실수방지", "사례"],
        "scenarios": ["소득이 애매할 때", "자녀 수가 기준선일 때", "배우자 이력이 있을 때", "혼인 시점이 걸릴 때", "출산 직후", "특공끼리 비교할 때"],
        "secondaries": ["소득기준", "자산기준", "부적격", "신혼희망타운", "우선공급", "가구원수"],
        "priority": 95,
    },
    "일반공급": {
        "audiences": ["무주택 실수요자", "저가점 청약자", "고가점 청약자", "1주택 갈아타기 준비자", "가점 낮은 청약자"],
        "intents": ["조건정리", "가능여부", "비교", "전략", "실수방지"],
        "scenarios": ["가점이 낮을 때", "추첨제 물량을 볼 때", "규제지역 청약 전", "당해가 애매할 때", "예비당첨 노릴 때", "커트라인이 걱정될 때"],
        "secondaries": ["가점제", "추첨제", "당해", "예비당첨", "커트라인", "당첨확률"],
        "priority": 92,
    },
    "규제": {
        "audiences": ["무주택 실수요자", "1주택 갈아타기 준비자", "분양권 매수 검토자", "청약초보", "실거주 예정자"],
        "intents": ["조건정리", "가능여부", "비교", "실수방지"],
        "scenarios": ["규제지역일 때", "당첨 이후", "매수 전에", "전매 계획이 있을 때", "입주 직전", "세대분리 직후"],
        "secondaries": ["재당첨 제한", "전매제한", "거주의무", "부적격", "주택수", "규제지역"],
        "priority": 90,
    },
    "자금": {
        "audiences": ["무주택 실수요자", "30대 맞벌이", "신혼부부", "저가점 청약자", "현금이 빠듯한 실수요자"],
        "intents": ["계산", "조건정리", "실수방지", "체크리스트", "사례"],
        "scenarios": ["계약금이 빠듯할 때", "중도금 대출이 필요할 때", "잔금이 걱정될 때", "월 상환액을 따질 때", "입주가 겹칠 때", "옵션비가 부담될 때"],
        "secondaries": ["계약금", "중도금", "잔금", "대출", "취득세", "옵션비", "현금흐름"],
        "priority": 93,
    },
    "대안": {
        "audiences": ["저가점 청약자", "무주택 실수요자", "1주택 갈아타기 준비자", "투자 겸 실거주 검토자", "당장 입주 필요한 수요자"],
        "intents": ["가능여부", "비교", "전략", "실수방지", "사례"],
        "scenarios": ["당첨이 어려울 때", "청약통장이 약할 때", "당장 입주가 필요할 때", "매수와 청약 사이에서 고민할 때", "무순위만 기다릴 때", "미분양 검토할 때"],
        "secondaries": ["무순위", "잔여세대", "분양권", "입주권", "미분양", "줍줍"],
        "priority": 88,
    },
    "실무": {
        "audiences": ["청약초보", "무주택 실수요자", "신혼부부", "사회초년생", "예비당첨자"],
        "intents": ["체크리스트", "실수방지", "조건정리", "FAQ"],
        "scenarios": ["청약 직전", "청약홈 접속 전", "서류 준비 전", "당첨 직후", "계약 직전", "예비당첨 연락 전"],
        "secondaries": ["입주자모집공고", "청약홈", "서류", "체크리스트", "당첨 후 절차", "기준일"],
        "priority": 91,
    },
    "세금": {
        "audiences": ["1주택 갈아타기 준비자", "무주택 실수요자", "분양권 매수 검토자", "실거주 예정자"],
        "intents": ["조건정리", "비교", "실수방지", "FAQ"],
        "scenarios": ["매수 전에", "입주 직전", "갈아타기할 때", "일시적 2주택이 될 때"],
        "secondaries": ["취득세", "양도세", "보유세", "일시적 2주택", "비과세"],
        "priority": 87,
    },
    "입지": {
        "audiences": ["실거주 예정자", "신혼부부", "30대 맞벌이", "투자 겸 실거주 검토자"],
        "intents": ["비교", "전략", "체크리스트", "사례"],
        "scenarios": ["실거주로 볼 때", "투자와 비교할 때", "입주 전 현장 볼 때", "교통이 애매할 때"],
        "secondaries": ["역세권", "학군", "생활권", "직주근접", "입지"],
        "priority": 80,
    },
    "당첨후": {
        "audiences": ["본당첨자", "예비당첨자", "무주택 실수요자", "1주택 갈아타기 준비자"],
        "intents": ["체크리스트", "실수방지", "조건정리", "FAQ"],
        "scenarios": ["당첨 직후", "계약 직전", "서류 보완 전", "포기 고민할 때"],
        "secondaries": ["계약 포기", "예비당첨", "서류 보완", "계약 일정", "부적격"],
        "priority": 89,
    },
    "공공분양": {
        "audiences": ["무주택 실수요자", "신혼부부", "청년 1인 가구", "생애최초 준비자"],
        "intents": ["조건정리", "비교", "가능여부", "실수방지"],
        "scenarios": ["공공분양 검토할 때", "민간분양과 비교할 때", "소득 기준이 애매할 때", "사전청약 이후 볼 때"],
        "secondaries": ["공공분양", "민간분양", "사전청약", "소득기준", "공급유형"],
        "priority": 86,
    },
    "민간분양": {
        "audiences": ["무주택 실수요자", "1주택 갈아타기 준비자", "30대 맞벌이", "실거주 예정자"],
        "intents": ["조건정리", "비교", "전략", "사례"],
        "scenarios": ["민간분양 볼 때", "규제지역에서 볼 때", "가점이 낮을 때", "실거주 목적으로 볼 때"],
        "secondaries": ["민간분양", "공공분양", "가점제", "추첨제", "입주자모집공고"],
        "priority": 85,
    },
    "임대": {
        "audiences": ["청년 1인 가구", "신혼부부", "무주택 실수요자", "사회초년생"],
        "intents": ["조건정리", "가능여부", "비교", "체크리스트"],
        "scenarios": ["공공임대 볼 때", "행복주택과 비교할 때", "소득기준이 애매할 때", "전세 대신 검토할 때"],
        "secondaries": ["공공임대", "행복주택", "국민임대", "매입임대", "소득기준"],
        "priority": 82,
    },
    "갈아타기": {
        "audiences": ["1주택 갈아타기 준비자", "실거주 예정자", "기존주택 처분 예정자", "전세 만기 예정자"],
        "intents": ["전략", "실수방지", "체크리스트", "사례"],
        "scenarios": ["기존 집 매도 전", "전세 만기 직전", "입주 일정이 겹칠 때", "자금이 묶일 때"],
        "secondaries": ["기존주택 처분", "전세 만기", "이사 일정", "거주의무", "잔금"],
        "priority": 84,
    },
    "확률분석": {
        "audiences": ["저가점 청약자", "고가점 청약자", "무주택 실수요자", "예비당첨 노리는 청약자"],
        "intents": ["전략", "비교", "계산", "FAQ"],
        "scenarios": ["경쟁률이 높을 때", "커트라인이 애매할 때", "예비당첨 노릴 때", "가점이 낮을 때"],
        "secondaries": ["당첨확률", "경쟁률", "가점", "예비당첨", "커트라인"],
        "priority": 83,
    },
}


@dataclass(frozen=True)
class TopicBlueprint:
    family: str
    primary_keyword: str
    secondary_keywords: tuple[str, ...] = ()
    audiences: tuple[str, ...] = ()
    intents: tuple[str, ...] = ()
    scenarios: tuple[str, ...] = ()
    comparison_keyword: str | None = None


TOPIC_BLUEPRINTS = [
    TopicBlueprint("기초", "청약통장", comparison_keyword="청년주택드림청약통장"),
    TopicBlueprint("기초", "무주택 기준", comparison_keyword="주택 수 판정"),
    TopicBlueprint("기초", "세대주 세대원", comparison_keyword="세대분리"),
    TopicBlueprint("기초", "1순위 조건", comparison_keyword="2순위"),
    TopicBlueprint("기초", "예치금", comparison_keyword="납입횟수"),
    TopicBlueprint("기초", "납입횟수", comparison_keyword="예치금"),
    TopicBlueprint("기초", "부양가족수", comparison_keyword="무주택기간"),
    TopicBlueprint("기초", "무주택기간", comparison_keyword="부양가족수"),
    TopicBlueprint("기초", "청약가점", comparison_keyword="추첨제"),
    TopicBlueprint("기초", "세대분리", comparison_keyword="세대주 세대원"),
    TopicBlueprint("실무", "입주자모집공고", comparison_keyword="청약홈"),
    TopicBlueprint("실무", "청약홈", comparison_keyword="입주자모집공고"),
    TopicBlueprint("실무", "서류 준비", comparison_keyword="기준일"),
    TopicBlueprint("실무", "기준일", comparison_keyword="서류 준비"),
    TopicBlueprint("실무", "예비당첨", comparison_keyword="본당첨"),
    TopicBlueprint("실무", "당첨 후 절차", comparison_keyword="계약 일정"),
    TopicBlueprint("특공", "신혼부부 특별공급", comparison_keyword="생애최초 특별공급"),
    TopicBlueprint("특공", "생애최초 특별공급", comparison_keyword="신혼부부 특별공급"),
    TopicBlueprint("특공", "다자녀 특별공급", comparison_keyword="노부모 부양 특별공급"),
    TopicBlueprint("특공", "노부모 부양 특별공급", comparison_keyword="다자녀 특별공급"),
    TopicBlueprint("특공", "기관추천 특별공급", comparison_keyword="일반공급"),
    TopicBlueprint("특공", "신생아 특별공급", comparison_keyword="신혼부부 특별공급"),
    TopicBlueprint("특공", "신혼희망타운", comparison_keyword="공공분양"),
    TopicBlueprint("특공", "특별공급 부적격", comparison_keyword="일반공급"),
    TopicBlueprint("일반공급", "가점제", comparison_keyword="추첨제"),
    TopicBlueprint("일반공급", "추첨제", comparison_keyword="가점제"),
    TopicBlueprint("일반공급", "당해", comparison_keyword="기타지역"),
    TopicBlueprint("일반공급", "예비당첨", comparison_keyword="본당첨"),
    TopicBlueprint("일반공급", "커트라인", comparison_keyword="당첨확률"),
    TopicBlueprint("일반공급", "당첨확률", comparison_keyword="커트라인"),
    TopicBlueprint("규제", "재당첨 제한", comparison_keyword="특별공급 1회 제한"),
    TopicBlueprint("규제", "전매제한", comparison_keyword="거주의무"),
    TopicBlueprint("규제", "거주의무", comparison_keyword="전매제한"),
    TopicBlueprint("규제", "부적격 당첨", comparison_keyword="중복당첨"),
    TopicBlueprint("규제", "중복당첨", comparison_keyword="부적격 당첨"),
    TopicBlueprint("규제", "주택 수 판정", comparison_keyword="무주택 기준"),
    TopicBlueprint("자금", "계약금 중도금 잔금", comparison_keyword="중도금 대출"),
    TopicBlueprint("자금", "중도금 대출", comparison_keyword="잔금 대출"),
    TopicBlueprint("자금", "잔금 대출", comparison_keyword="중도금 대출"),
    TopicBlueprint("자금", "취득세", comparison_keyword="양도세"),
    TopicBlueprint("자금", "월 상환액", comparison_keyword="자기자본"),
    TopicBlueprint("자금", "옵션비", comparison_keyword="발코니 확장"),
    TopicBlueprint("자금", "발코니 확장", comparison_keyword="옵션비"),
    TopicBlueprint("자금", "현금흐름", comparison_keyword="월 상환액"),
    TopicBlueprint("대안", "무순위 청약", comparison_keyword="잔여세대"),
    TopicBlueprint("대안", "잔여세대", comparison_keyword="무순위 청약"),
    TopicBlueprint("대안", "분양권", comparison_keyword="입주권"),
    TopicBlueprint("대안", "입주권", comparison_keyword="분양권"),
    TopicBlueprint("대안", "미분양", comparison_keyword="무순위 청약"),
    TopicBlueprint("대안", "줍줍", comparison_keyword="무순위 청약"),
    TopicBlueprint("세금", "취득세", comparison_keyword="보유세"),
    TopicBlueprint("세금", "양도세", comparison_keyword="취득세"),
    TopicBlueprint("세금", "보유세", comparison_keyword="취득세"),
    TopicBlueprint("세금", "일시적 2주택", comparison_keyword="비과세"),
    TopicBlueprint("세금", "비과세", comparison_keyword="일시적 2주택"),
    TopicBlueprint("입지", "역세권", comparison_keyword="직주근접"),
    TopicBlueprint("입지", "학군", comparison_keyword="생활권"),
    TopicBlueprint("입지", "생활권", comparison_keyword="학군"),
    TopicBlueprint("입지", "직주근접", comparison_keyword="역세권"),
    TopicBlueprint("당첨후", "계약 포기", comparison_keyword="재당첨 제한"),
    TopicBlueprint("당첨후", "서류 보완", comparison_keyword="부적격 당첨"),
    TopicBlueprint("당첨후", "계약 일정", comparison_keyword="당첨 후 절차"),
    TopicBlueprint("당첨후", "예비당첨 연락", comparison_keyword="예비당첨"),
    TopicBlueprint("기초", "청약 가능 지역", comparison_keyword="당해 기타지역"),
    TopicBlueprint("기초", "세대원 기준", comparison_keyword="세대주 기준"),
    TopicBlueprint("기초", "청약통장 해지", comparison_keyword="당첨 후 절차"),
    TopicBlueprint("특공", "다자녀 기준", comparison_keyword="노부모 부양 기준"),
    TopicBlueprint("특공", "혼인기간", comparison_keyword="소득기준"),
    TopicBlueprint("특공", "가구원수", comparison_keyword="소득기준"),
    TopicBlueprint("일반공급", "해당지역 우선", comparison_keyword="기타지역"),
    TopicBlueprint("일반공급", "청약 경쟁률", comparison_keyword="가점 커트라인"),
    TopicBlueprint("일반공급", "예비당첨 순번", comparison_keyword="본당첨"),
    TopicBlueprint("규제", "규제지역", comparison_keyword="비규제지역"),
    TopicBlueprint("규제", "비규제지역", comparison_keyword="규제지역"),
    TopicBlueprint("규제", "주택 수", comparison_keyword="무주택 기준"),
    TopicBlueprint("자금", "자기자본", comparison_keyword="월 상환액"),
    TopicBlueprint("자금", "잔금 부족", comparison_keyword="중도금 대출"),
    TopicBlueprint("자금", "이사비", comparison_keyword="옵션비"),
    TopicBlueprint("세금", "종합부동산세", comparison_keyword="재산세"),
    TopicBlueprint("세금", "재산세", comparison_keyword="종합부동산세"),
    TopicBlueprint("세금", "양도세 비과세", comparison_keyword="일시적 2주택"),
    TopicBlueprint("입지", "역세권 실거주", comparison_keyword="직주근접"),
    TopicBlueprint("입지", "학군 실거주", comparison_keyword="생활권"),
    TopicBlueprint("입지", "생활 인프라", comparison_keyword="교통"),
    TopicBlueprint("입지", "직주근접", comparison_keyword="생활 인프라"),
    TopicBlueprint("실무", "청약홈 신청내역", comparison_keyword="입주자모집공고"),
    TopicBlueprint("실무", "주민등록등본 초본", comparison_keyword="가족관계증명서"),
    TopicBlueprint("실무", "서류 기준일", comparison_keyword="공고일"),
    TopicBlueprint("당첨후", "당첨 후 서류", comparison_keyword="서류 보완"),
    TopicBlueprint("당첨후", "계약금 납부일", comparison_keyword="계약 일정"),
    TopicBlueprint("당첨후", "당첨 취소", comparison_keyword="계약 포기"),
    TopicBlueprint("공공분양", "공공분양", comparison_keyword="민간분양"),
    TopicBlueprint("공공분양", "사전청약", comparison_keyword="본청약"),
    TopicBlueprint("공공분양", "공공분양 소득기준", comparison_keyword="민간분양"),
    TopicBlueprint("민간분양", "민간분양", comparison_keyword="공공분양"),
    TopicBlueprint("민간분양", "분양가상한제", comparison_keyword="민간분양"),
    TopicBlueprint("민간분양", "민영주택", comparison_keyword="국민주택"),
    TopicBlueprint("임대", "공공임대", comparison_keyword="행복주택"),
    TopicBlueprint("임대", "행복주택", comparison_keyword="국민임대"),
    TopicBlueprint("임대", "국민임대", comparison_keyword="공공임대"),
    TopicBlueprint("임대", "매입임대", comparison_keyword="전세임대"),
    TopicBlueprint("임대", "전세임대", comparison_keyword="매입임대"),
    TopicBlueprint("갈아타기", "기존주택 처분", comparison_keyword="거주의무"),
    TopicBlueprint("갈아타기", "전세 만기", comparison_keyword="이사 일정"),
    TopicBlueprint("갈아타기", "이사 일정", comparison_keyword="잔금 일정"),
    TopicBlueprint("갈아타기", "잔금 일정", comparison_keyword="기존주택 처분"),
    TopicBlueprint("확률분석", "당첨확률", comparison_keyword="경쟁률"),
    TopicBlueprint("확률분석", "경쟁률", comparison_keyword="커트라인"),
    TopicBlueprint("확률분석", "커트라인", comparison_keyword="예비당첨"),
    TopicBlueprint("확률분석", "예비당첨 확률", comparison_keyword="본당첨"),
]

DEFAULT_DOMAIN = "cheongyak"
AUCTION_DOMAIN = "auction"
SUPPORTED_DOMAINS = (DEFAULT_DOMAIN, AUCTION_DOMAIN)

AUCTION_FAMILY_PRESETS = {
    "경매기초": {
        "audiences": ["경매초보", "처음 입찰하는 실수요자", "소액 투자자", "직장인 투자자", "무주택 실수요자", "은퇴 준비자"],
        "intents": ["조건정리", "가능여부", "비교", "실수방지", "체크리스트"],
        "scenarios": ["처음 물건을 볼 때", "법원경매 사이트를 볼 때", "입찰 전날", "용어가 헷갈릴 때", "무료 사이트로 검색할 때", "공부 순서를 잡을 때"],
        "secondaries": ["법원경매정보", "사건번호", "매각기일", "최저매각가격", "입찰표", "입찰보증금"],
        "priority": 100,
    },
    "물건검색": {
        "audiences": ["경매초보", "직장인 투자자", "실거주 매수자", "소액 투자자", "임장 전 독자"],
        "intents": ["조건정리", "체크리스트", "실수방지", "비교", "사례"],
        "scenarios": ["물건 검색을 시작할 때", "사건번호를 봤을 때", "매각물건명세서를 볼 때", "임장 전에", "시세를 비교할 때", "무료 정보만 볼 때"],
        "secondaries": ["매각물건명세서", "현황조사서", "감정평가서", "등기부등본", "전입세대열람", "시세조사"],
        "priority": 97,
    },
    "입찰실무": {
        "audiences": ["처음 입찰하는 실수요자", "경매초보", "직장인 투자자", "부부 공동입찰자", "소액 투자자"],
        "intents": ["체크리스트", "실수방지", "조건정리", "가능여부", "FAQ"],
        "scenarios": ["입찰표를 쓸 때", "법원에 가기 전", "보증금을 준비할 때", "개찰 결과를 기다릴 때", "유찰 후 다시 볼 때", "공동 입찰을 할 때"],
        "secondaries": ["입찰표", "입찰보증금", "매각기일", "개찰", "차순위매수신고", "매각허가결정"],
        "priority": 96,
    },
    "권리분석": {
        "audiences": ["경매초보", "권리분석 입문자", "실거주 매수자", "소액 투자자", "위험 회피형 투자자"],
        "intents": ["조건정리", "가능여부", "비교", "실수방지", "사례", "FAQ"],
        "scenarios": ["등기부등본을 볼 때", "말소기준권리를 찾을 때", "인수 권리가 의심될 때", "등기 순위가 헷갈릴 때", "입찰 전 최종 점검할 때", "특수권리가 보일 때"],
        "secondaries": ["말소기준권리", "근저당", "가압류", "가처분", "전세권", "임차권등기", "인수되는 권리"],
        "priority": 99,
    },
    "임차인배당": {
        "audiences": ["경매초보", "실거주 매수자", "전세보증금이 걱정되는 독자", "권리분석 입문자", "위험 회피형 투자자"],
        "intents": ["조건정리", "가능여부", "비교", "실수방지", "사례", "FAQ"],
        "scenarios": ["선순위 임차인이 있을 때", "배당요구 여부가 헷갈릴 때", "전입일자를 볼 때", "보증금 인수가 걱정될 때", "명세서와 등기부가 다를 때", "전세사기 물건을 볼 때"],
        "secondaries": ["선순위 임차인", "대항력", "우선변제권", "확정일자", "배당요구", "배당요구종기", "보증금 인수"],
        "priority": 98,
    },
    "명도점유": {
        "audiences": ["낙찰 예정자", "처음 입찰하는 실수요자", "실거주 매수자", "소액 투자자", "명도가 걱정되는 독자"],
        "intents": ["조건정리", "실수방지", "체크리스트", "사례", "FAQ"],
        "scenarios": ["낙찰 직후", "점유자를 만날 때", "인도명령을 준비할 때", "명도비를 협의할 때", "협의가 안 될 때", "강제집행 전"],
        "secondaries": ["인도명령", "점유자", "명도비", "명도소송", "강제집행", "내용증명", "이사비"],
        "priority": 95,
    },
    "자금세금": {
        "audiences": ["직장인 투자자", "소액 투자자", "실거주 매수자", "현금이 빠듯한 낙찰 예정자", "은퇴 준비자"],
        "intents": ["계산", "조건정리", "실수방지", "체크리스트", "사례"],
        "scenarios": ["입찰가를 정할 때", "잔금 대출을 알아볼 때", "취득세를 계산할 때", "잔금납부기한이 다가올 때", "수리비가 걱정될 때", "체납 관리비를 볼 때"],
        "secondaries": ["경락잔금대출", "잔금납부", "취득세", "법무비용", "수리비", "관리비 체납", "DSR"],
        "priority": 94,
    },
    "수익분석": {
        "audiences": ["직장인 투자자", "소액 투자자", "임대수익 검토자", "실거주 매수자", "위험 회피형 투자자"],
        "intents": ["계산", "비교", "전략", "실수방지", "사례"],
        "scenarios": ["감정가가 높아 보일 때", "유찰 물건을 볼 때", "낙찰가율을 비교할 때", "입찰가를 정할 때", "임대수익을 계산할 때", "매도 시나리오를 잡을 때"],
        "secondaries": ["낙찰가율", "감정가", "시세조사", "수익률 계산", "입찰가 산정", "안전마진", "유찰"],
        "priority": 93,
    },
    "물건유형": {
        "audiences": ["실거주 매수자", "직장인 투자자", "소액 투자자", "상가 투자 검토자", "토지 투자 검토자"],
        "intents": ["비교", "조건정리", "실수방지", "전략", "사례"],
        "scenarios": ["아파트와 빌라를 비교할 때", "상가 공실이 걱정될 때", "토지 규제를 볼 때", "오피스텔 수익률을 볼 때", "공장 물건을 볼 때", "전원주택을 볼 때"],
        "secondaries": ["아파트 경매", "빌라 경매", "오피스텔 경매", "상가 경매", "토지 경매", "공장 경매", "다가구"],
        "priority": 92,
    },
    "특수물건": {
        "audiences": ["권리분석 입문자", "위험 회피형 투자자", "중급 경매 투자자", "소액 투자자", "토지 투자 검토자"],
        "intents": ["가능여부", "비교", "실수방지", "조건정리", "사례", "FAQ"],
        "scenarios": ["특수권리가 보일 때", "입찰을 피해야 할지 볼 때", "권리 인수가 걱정될 때", "토지와 건물이 따로 보일 때", "공유지분을 볼 때", "농지 물건을 볼 때"],
        "secondaries": ["유치권", "법정지상권", "분묘기지권", "지분경매", "공유자우선매수권", "농지취득자격증명", "대지권미등기"],
        "priority": 91,
    },
    "낙찰후": {
        "audiences": ["낙찰 예정자", "낙찰 직후 독자", "실거주 매수자", "직장인 투자자", "명도가 걱정되는 독자"],
        "intents": ["체크리스트", "조건정리", "실수방지", "사례", "FAQ"],
        "scenarios": ["낙찰 직후", "매각허가결정 후", "잔금 납부 전", "소유권이전 전", "배당기일 전", "수리 후 임대 전"],
        "secondaries": ["낙찰 후 절차", "잔금납부", "소유권이전", "배당기일", "인도명령 신청", "명도 협상", "수리 후 임대"],
        "priority": 90,
    },
    "학습실패": {
        "audiences": ["경매초보", "부동산경매 입문자", "직장인 투자자", "소액 투자자", "위험 회피형 투자자"],
        "intents": ["조건정리", "실수방지", "체크리스트", "비교", "FAQ"],
        "scenarios": ["경매 공부를 시작할 때", "강의와 독학을 비교할 때", "첫 입찰을 앞둘 때", "실패 사례를 볼 때", "무리한 수익률이 보일 때", "기초 용어가 헷갈릴 때"],
        "secondaries": ["경매 강의", "경매 책", "경매 공부 순서", "경매 실패", "경매 위험성", "권리분석", "명도"],
        "priority": 89,
    },
    "사이트비교": {
        "audiences": ["경매초보", "직장인 투자자", "실거주 매수자", "소액 투자자", "공매 입문자"],
        "intents": ["사이트탐색", "비교", "조건정리", "실수방지", "체크리스트"],
        "scenarios": ["무료 사이트만 볼 때", "유료 경매 사이트를 비교할 때", "사건번호를 검색할 때", "모바일로 물건을 찾을 때", "알림 기능을 고를 때", "공매 사이트를 같이 볼 때"],
        "secondaries": ["대법원 경매정보", "법원경매정보", "경매마당", "굿옥션", "지지옥션", "두인경매", "온비드"],
        "priority": 88,
    },
    "지역법원": {
        "audiences": ["지역 실거주 매수자", "직장인 투자자", "소액 투자자", "임장 전 독자", "경매초보"],
        "intents": ["지역물건탐색", "조건정리", "체크리스트", "실수방지", "비교"],
        "scenarios": ["지역 물건을 처음 검색할 때", "법원 관할을 확인할 때", "임장 동선을 잡을 때", "아파트와 빌라를 비교할 때", "지방법원 경매계를 볼 때", "낙찰가율을 비교할 때"],
        "secondaries": ["지방법원 경매", "아파트 경매", "빌라 경매", "낙찰가율", "임장 체크리스트", "매각기일", "사건번호"],
        "priority": 87,
    },
    "공매비교": {
        "audiences": ["경매초보", "공매 입문자", "직장인 투자자", "소액 투자자", "위험 회피형 투자자"],
        "intents": ["비교", "조건정리", "가능여부", "실수방지", "FAQ"],
        "scenarios": ["온비드 물건을 볼 때", "경매와 공매를 비교할 때", "압류재산 공매를 볼 때", "공매 낙찰 후", "인수 권리가 걱정될 때", "입찰 방식이 헷갈릴 때"],
        "secondaries": ["온비드 공매", "공매 낙찰 후 절차", "압류재산 공매", "경매 공매 차이", "공매 인수되는 권리"],
        "priority": 86,
    },
}

AUCTION_TOPIC_BLUEPRINTS = [
    TopicBlueprint("경매기초", "부동산 경매", comparison_keyword="법원경매"),
    TopicBlueprint("경매기초", "법원경매", comparison_keyword="공매"),
    TopicBlueprint("경매기초", "법원경매정보", comparison_keyword="무료 경매 사이트"),
    TopicBlueprint("경매기초", "경매 사건 조회", comparison_keyword="사건번호"),
    TopicBlueprint("경매기초", "경매 물건 검색", comparison_keyword="법원경매정보"),
    TopicBlueprint("경매기초", "경매 용어", comparison_keyword="경매 절차"),
    TopicBlueprint("경매기초", "경매 절차", comparison_keyword="낙찰 후 절차"),
    TopicBlueprint("경매기초", "경매 입문", comparison_keyword="경매 공부"),
    TopicBlueprint("경매기초", "경매 공부", comparison_keyword="권리분석"),
    TopicBlueprint("경매기초", "경매 체크리스트", comparison_keyword="입찰 전 점검"),
    TopicBlueprint("경매기초", "경매 사이트", comparison_keyword="무료 경매 사이트"),
    TopicBlueprint("경매기초", "무료 경매 사이트", comparison_keyword="법원경매정보"),
    TopicBlueprint("경매기초", "경매 위험성", comparison_keyword="경매 실패 사례"),
    TopicBlueprint("물건검색", "매각물건명세서", comparison_keyword="현황조사서"),
    TopicBlueprint("물건검색", "현황조사서", comparison_keyword="매각물건명세서"),
    TopicBlueprint("물건검색", "감정평가서", comparison_keyword="감정가"),
    TopicBlueprint("물건검색", "등기부등본 경매", comparison_keyword="권리분석"),
    TopicBlueprint("물건검색", "전입세대열람", comparison_keyword="선순위 임차인"),
    TopicBlueprint("물건검색", "임장 체크리스트", comparison_keyword="시세조사"),
    TopicBlueprint("물건검색", "경매 시세조사", comparison_keyword="감정가"),
    TopicBlueprint("물건검색", "낙찰가율 통계", comparison_keyword="유찰"),
    TopicBlueprint("물건검색", "최저매각가격", comparison_keyword="감정가"),
    TopicBlueprint("물건검색", "감정가", comparison_keyword="실거래가"),
    TopicBlueprint("입찰실무", "매각기일", comparison_keyword="입찰일"),
    TopicBlueprint("입찰실무", "입찰표 작성", comparison_keyword="입찰보증금"),
    TopicBlueprint("입찰실무", "공동 입찰표", comparison_keyword="대리 입찰"),
    TopicBlueprint("입찰실무", "입찰보증금", comparison_keyword="보증금 반환"),
    TopicBlueprint("입찰실무", "입찰보증금 반환", comparison_keyword="입찰 무효"),
    TopicBlueprint("입찰실무", "기일입찰", comparison_keyword="기간입찰"),
    TopicBlueprint("입찰실무", "개찰", comparison_keyword="최고가매수신고인"),
    TopicBlueprint("입찰실무", "최고가매수신고인", comparison_keyword="차순위매수신고"),
    TopicBlueprint("입찰실무", "차순위매수신고", comparison_keyword="재매각"),
    TopicBlueprint("입찰실무", "매각허가결정", comparison_keyword="매각불허가"),
    TopicBlueprint("입찰실무", "매각불허가", comparison_keyword="매각허가결정"),
    TopicBlueprint("입찰실무", "유찰", comparison_keyword="최저매각가격"),
    TopicBlueprint("입찰실무", "재매각", comparison_keyword="입찰보증금"),
    TopicBlueprint("권리분석", "권리분석", comparison_keyword="말소기준권리"),
    TopicBlueprint("권리분석", "말소기준권리", comparison_keyword="근저당"),
    TopicBlueprint("권리분석", "근저당", comparison_keyword="가압류"),
    TopicBlueprint("권리분석", "근저당권 말소", comparison_keyword="말소기준권리"),
    TopicBlueprint("권리분석", "압류", comparison_keyword="가압류"),
    TopicBlueprint("권리분석", "가압류", comparison_keyword="압류"),
    TopicBlueprint("권리분석", "가처분", comparison_keyword="선순위 가처분"),
    TopicBlueprint("권리분석", "전세권", comparison_keyword="임차권등기"),
    TopicBlueprint("권리분석", "임차권등기", comparison_keyword="대항력"),
    TopicBlueprint("권리분석", "인수되는 권리", comparison_keyword="소멸되는 권리"),
    TopicBlueprint("권리분석", "소멸되는 권리", comparison_keyword="인수되는 권리"),
    TopicBlueprint("권리분석", "토지별도등기", comparison_keyword="대지권미등기"),
    TopicBlueprint("권리분석", "대지권미등기", comparison_keyword="토지별도등기"),
    TopicBlueprint("임차인배당", "선순위 임차인", comparison_keyword="후순위 임차인"),
    TopicBlueprint("임차인배당", "대항력 있는 임차인", comparison_keyword="배당요구"),
    TopicBlueprint("임차인배당", "후순위 임차인", comparison_keyword="선순위 임차인"),
    TopicBlueprint("임차인배당", "우선변제권", comparison_keyword="확정일자"),
    TopicBlueprint("임차인배당", "확정일자", comparison_keyword="전입일자"),
    TopicBlueprint("임차인배당", "배당요구", comparison_keyword="배당요구종기"),
    TopicBlueprint("임차인배당", "배당요구종기", comparison_keyword="선순위 임차인"),
    TopicBlueprint("임차인배당", "배당표", comparison_keyword="배당기일"),
    TopicBlueprint("임차인배당", "보증금 인수", comparison_keyword="대항력"),
    TopicBlueprint("임차인배당", "전세사기 경매", comparison_keyword="선순위 임차인"),
    TopicBlueprint("명도점유", "명도", comparison_keyword="인도명령"),
    TopicBlueprint("명도점유", "인도명령", comparison_keyword="명도소송"),
    TopicBlueprint("명도점유", "점유자", comparison_keyword="인도명령"),
    TopicBlueprint("명도점유", "명도비", comparison_keyword="이사비"),
    TopicBlueprint("명도점유", "명도소송", comparison_keyword="인도명령"),
    TopicBlueprint("명도점유", "강제집행", comparison_keyword="명도소송"),
    TopicBlueprint("명도점유", "내용증명", comparison_keyword="명도 협상"),
    TopicBlueprint("명도점유", "이사비", comparison_keyword="명도비"),
    TopicBlueprint("명도점유", "점유이전금지가처분", comparison_keyword="강제집행"),
    TopicBlueprint("명도점유", "유체동산 경매", comparison_keyword="강제집행"),
    TopicBlueprint("자금세금", "경락잔금대출", comparison_keyword="경매 대출"),
    TopicBlueprint("자금세금", "경매 대출", comparison_keyword="경락잔금대출"),
    TopicBlueprint("자금세금", "DSR", comparison_keyword="경락잔금대출"),
    TopicBlueprint("자금세금", "LTV", comparison_keyword="경락잔금대출"),
    TopicBlueprint("자금세금", "잔금납부", comparison_keyword="잔금납부기한"),
    TopicBlueprint("자금세금", "잔금납부기한", comparison_keyword="재매각"),
    TopicBlueprint("자금세금", "취득세", comparison_keyword="법무비용"),
    TopicBlueprint("자금세금", "법무비용", comparison_keyword="취득세"),
    TopicBlueprint("자금세금", "수리비", comparison_keyword="안전마진"),
    TopicBlueprint("자금세금", "관리비 체납", comparison_keyword="보증금 인수"),
    TopicBlueprint("수익분석", "낙찰가율", comparison_keyword="감정가"),
    TopicBlueprint("수익분석", "감정가", comparison_keyword="실거래가"),
    TopicBlueprint("수익분석", "수익률 계산", comparison_keyword="입찰가 산정"),
    TopicBlueprint("수익분석", "임대수익률", comparison_keyword="공실률"),
    TopicBlueprint("수익분석", "매도 시나리오", comparison_keyword="임대 시나리오"),
    TopicBlueprint("수익분석", "입찰가 산정", comparison_keyword="안전마진"),
    TopicBlueprint("수익분석", "안전마진", comparison_keyword="낙찰가율"),
    TopicBlueprint("수익분석", "유찰가 판단", comparison_keyword="최저매각가격"),
    TopicBlueprint("수익분석", "대출 이자", comparison_keyword="수익률 계산"),
    TopicBlueprint("물건유형", "아파트 경매", comparison_keyword="빌라 경매"),
    TopicBlueprint("물건유형", "빌라 경매", comparison_keyword="아파트 경매"),
    TopicBlueprint("물건유형", "오피스텔 경매", comparison_keyword="상가 경매"),
    TopicBlueprint("물건유형", "상가 경매", comparison_keyword="오피스텔 경매"),
    TopicBlueprint("물건유형", "토지 경매", comparison_keyword="농지취득자격증명"),
    TopicBlueprint("물건유형", "공장 경매", comparison_keyword="유치권"),
    TopicBlueprint("물건유형", "다가구 경매", comparison_keyword="다세대 경매"),
    TopicBlueprint("물건유형", "다세대 경매", comparison_keyword="다가구 경매"),
    TopicBlueprint("물건유형", "전원주택 경매", comparison_keyword="토지 경매"),
    TopicBlueprint("물건유형", "자동차 경매", comparison_keyword="법원경매"),
    TopicBlueprint("특수물건", "유치권", comparison_keyword="법정지상권"),
    TopicBlueprint("특수물건", "유치권 행사", comparison_keyword="유치권"),
    TopicBlueprint("특수물건", "법정지상권", comparison_keyword="토지 경매"),
    TopicBlueprint("특수물건", "분묘기지권", comparison_keyword="토지 경매"),
    TopicBlueprint("특수물건", "지분경매", comparison_keyword="공유자우선매수권"),
    TopicBlueprint("특수물건", "공유자우선매수권", comparison_keyword="지분경매"),
    TopicBlueprint("특수물건", "농지취득자격증명", comparison_keyword="토지 경매"),
    TopicBlueprint("특수물건", "위반건축물", comparison_keyword="대출 제한"),
    TopicBlueprint("특수물건", "선순위 가처분", comparison_keyword="가처분"),
    TopicBlueprint("특수물건", "별도등기", comparison_keyword="토지별도등기"),
    TopicBlueprint("특수물건", "건물만 경매", comparison_keyword="법정지상권"),
    TopicBlueprint("특수물건", "토지만 경매", comparison_keyword="법정지상권"),
    TopicBlueprint("낙찰후", "낙찰 후 절차", comparison_keyword="잔금납부"),
    TopicBlueprint("낙찰후", "매각대금납부", comparison_keyword="잔금납부"),
    TopicBlueprint("낙찰후", "소유권이전", comparison_keyword="소유권이전등기"),
    TopicBlueprint("낙찰후", "소유권이전등기", comparison_keyword="취득세"),
    TopicBlueprint("낙찰후", "배당기일", comparison_keyword="배당표"),
    TopicBlueprint("낙찰후", "인도명령 신청", comparison_keyword="명도"),
    TopicBlueprint("낙찰후", "명도 협상", comparison_keyword="명도비"),
    TopicBlueprint("낙찰후", "세입자 협의", comparison_keyword="명도 협상"),
    TopicBlueprint("낙찰후", "수리 후 임대", comparison_keyword="임대수익률"),
    TopicBlueprint("학습실패", "경매 강의", comparison_keyword="경매 독학"),
    TopicBlueprint("학습실패", "경매 강의 추천", comparison_keyword="경매 책 추천"),
    TopicBlueprint("학습실패", "부동산 경매 공부", comparison_keyword="경매 공부 순서"),
    TopicBlueprint("학습실패", "경매 책", comparison_keyword="경매 강의"),
    TopicBlueprint("학습실패", "경매 책 추천", comparison_keyword="경매 강의 추천"),
    TopicBlueprint("학습실패", "경매 자격증", comparison_keyword="경매사"),
    TopicBlueprint("학습실패", "부동산 경매 자격증", comparison_keyword="경매사 자격증"),
    TopicBlueprint("학습실패", "경매 실패", comparison_keyword="경매 위험성"),
    TopicBlueprint("학습실패", "경매 사기", comparison_keyword="경매 주의사항"),
    TopicBlueprint("학습실패", "경매 위험성", comparison_keyword="권리분석"),
    TopicBlueprint("학습실패", "경매 주의사항", comparison_keyword="입찰 전 체크리스트"),
    TopicBlueprint("학습실패", "경매 용어", comparison_keyword="입찰보증금"),
    TopicBlueprint("사이트비교", "대법원 경매", comparison_keyword="법원경매정보"),
    TopicBlueprint("사이트비교", "대법원 경매정보", comparison_keyword="법원경매정보"),
    TopicBlueprint("사이트비교", "대법원 경매사건검색", comparison_keyword="경매 사건 조회"),
    TopicBlueprint("사이트비교", "대법원 경매사이트", comparison_keyword="무료 경매 사이트"),
    TopicBlueprint("사이트비교", "경매마당", comparison_keyword="법원경매정보"),
    TopicBlueprint("사이트비교", "굿옥션 경매", comparison_keyword="경매마당"),
    TopicBlueprint("사이트비교", "지지옥션", comparison_keyword="굿옥션"),
    TopicBlueprint("사이트비교", "두인경매", comparison_keyword="경매마당"),
    TopicBlueprint("사이트비교", "마이옥션", comparison_keyword="지지옥션"),
    TopicBlueprint("사이트비교", "옥션원 경매", comparison_keyword="경매마당"),
    TopicBlueprint("사이트비교", "탱크옥션", comparison_keyword="굿옥션"),
    TopicBlueprint("사이트비교", "스피드옥션", comparison_keyword="마이옥션"),
    TopicBlueprint("지역법원", "서울 경매", comparison_keyword="서울 아파트 경매"),
    TopicBlueprint("지역법원", "서울 아파트 경매", comparison_keyword="서울 다가구 경매"),
    TopicBlueprint("지역법원", "서울중앙지방법원 경매", comparison_keyword="서울 경매"),
    TopicBlueprint("지역법원", "서울남부지방법원 경매", comparison_keyword="서울 경매"),
    TopicBlueprint("지역법원", "서울동부지방법원 경매", comparison_keyword="서울 경매"),
    TopicBlueprint("지역법원", "서울북부지방법원 경매", comparison_keyword="서울 경매"),
    TopicBlueprint("지역법원", "서울서부지방법원 경매", comparison_keyword="서울 경매"),
    TopicBlueprint("지역법원", "경기도 경매", comparison_keyword="수원지방법원 경매"),
    TopicBlueprint("지역법원", "수원 경매", comparison_keyword="수원지방법원 경매"),
    TopicBlueprint("지역법원", "수원지방법원 경매", comparison_keyword="경기도 경매"),
    TopicBlueprint("지역법원", "성남 경매", comparison_keyword="분당 아파트 경매"),
    TopicBlueprint("지역법원", "분당 경매", comparison_keyword="성남 경매"),
    TopicBlueprint("지역법원", "용인 경매", comparison_keyword="수원지방법원 경매"),
    TopicBlueprint("지역법원", "고양 경매", comparison_keyword="일산 경매"),
    TopicBlueprint("지역법원", "일산 경매", comparison_keyword="고양 경매"),
    TopicBlueprint("지역법원", "부천 경매", comparison_keyword="인천지방법원 경매"),
    TopicBlueprint("지역법원", "안산 경매", comparison_keyword="수원지방법원 경매"),
    TopicBlueprint("지역법원", "평택 경매", comparison_keyword="수원지방법원 경매"),
    TopicBlueprint("지역법원", "화성 경매", comparison_keyword="수원지방법원 경매"),
    TopicBlueprint("지역법원", "김포 경매", comparison_keyword="인천지방법원 경매"),
    TopicBlueprint("지역법원", "파주 경매", comparison_keyword="의정부지방법원 경매"),
    TopicBlueprint("지역법원", "의정부 경매", comparison_keyword="의정부지방법원 경매"),
    TopicBlueprint("지역법원", "남양주 경매", comparison_keyword="의정부지방법원 경매"),
    TopicBlueprint("지역법원", "안양 경매", comparison_keyword="수원지방법원 경매"),
    TopicBlueprint("지역법원", "시흥 경매", comparison_keyword="안산 경매"),
    TopicBlueprint("지역법원", "광명 경매", comparison_keyword="안양 경매"),
    TopicBlueprint("지역법원", "하남 경매", comparison_keyword="성남 경매"),
    TopicBlueprint("지역법원", "인천 경매", comparison_keyword="인천지방법원 경매"),
    TopicBlueprint("지역법원", "인천지방법원 경매", comparison_keyword="인천 경매"),
    TopicBlueprint("지역법원", "부산 경매", comparison_keyword="부산지방법원 경매"),
    TopicBlueprint("지역법원", "부산지방법원 경매", comparison_keyword="부산 경매"),
    TopicBlueprint("지역법원", "대구 경매", comparison_keyword="대구지방법원 경매"),
    TopicBlueprint("지역법원", "대구지방법원 경매", comparison_keyword="대구 경매"),
    TopicBlueprint("지역법원", "대전 경매", comparison_keyword="대전지방법원 경매"),
    TopicBlueprint("지역법원", "대전지방법원 경매", comparison_keyword="대전 경매"),
    TopicBlueprint("지역법원", "광주 경매", comparison_keyword="광주지방법원 경매"),
    TopicBlueprint("지역법원", "광주지방법원 경매", comparison_keyword="광주 경매"),
    TopicBlueprint("지역법원", "울산 경매", comparison_keyword="울산 아파트 경매"),
    TopicBlueprint("지역법원", "세종 경매", comparison_keyword="대전지방법원 경매"),
    TopicBlueprint("지역법원", "제주 경매", comparison_keyword="제주지방법원 경매"),
    TopicBlueprint("지역법원", "제주지방법원 경매", comparison_keyword="제주 경매"),
    TopicBlueprint("지역법원", "천안 경매", comparison_keyword="천안 경매물건"),
    TopicBlueprint("지역법원", "아산 경매", comparison_keyword="천안 경매"),
    TopicBlueprint("지역법원", "청주 경매", comparison_keyword="청주지방법원 경매"),
    TopicBlueprint("지역법원", "청주지방법원 경매", comparison_keyword="청주 경매"),
    TopicBlueprint("지역법원", "전주 경매", comparison_keyword="전주 법원 경매"),
    TopicBlueprint("지역법원", "전주지방법원 경매", comparison_keyword="전주 경매"),
    TopicBlueprint("지역법원", "창원 경매", comparison_keyword="창원지방법원 경매"),
    TopicBlueprint("지역법원", "창원지방법원 경매", comparison_keyword="창원 경매"),
    TopicBlueprint("지역법원", "김해 경매", comparison_keyword="창원지방법원 경매"),
    TopicBlueprint("지역법원", "포항 경매", comparison_keyword="포항 법원 경매"),
    TopicBlueprint("지역법원", "구미 경매", comparison_keyword="구미 아파트 경매"),
    TopicBlueprint("지역법원", "원주 경매", comparison_keyword="원주 경매 아파트"),
    TopicBlueprint("지역법원", "춘천 경매", comparison_keyword="춘천지방법원 경매"),
    TopicBlueprint("공매비교", "온비드 공매", comparison_keyword="법원경매"),
    TopicBlueprint("공매비교", "공매 낙찰 후 절차", comparison_keyword="경매 낙찰 후 절차"),
    TopicBlueprint("공매비교", "공매 인수되는 권리", comparison_keyword="경매 인수되는 권리"),
    TopicBlueprint("공매비교", "경매 공매 차이", comparison_keyword="온비드 공매"),
    TopicBlueprint("공매비교", "압류재산 공매", comparison_keyword="온비드 공매"),
]

DOMAIN_FAMILY_PRESETS = {
    DEFAULT_DOMAIN: FAMILY_PRESETS,
    AUCTION_DOMAIN: AUCTION_FAMILY_PRESETS,
}

DOMAIN_TOPIC_BLUEPRINTS = {
    DEFAULT_DOMAIN: TOPIC_BLUEPRINTS,
    AUCTION_DOMAIN: AUCTION_TOPIC_BLUEPRINTS,
}
