from __future__ import annotations

from dataclasses import dataclass

NAVER_SEO_SECTIONS = [
    "상단 요약",
    "이 글에서 바로 답하는 질문",
    "핵심 조건 정리",
    "헷갈리기 쉬운 예외",
    "실전 예시 시나리오",
    "체크리스트",
    "FAQ",
    "마무리 결론",
]

ANGLE_PROMPTS = {
    "판단형": "첫 2문단에서 가능/불가 또는 유리/불리를 명확히 결론내립니다.",
    "비교형": "비슷한 제도나 상황과 비교해 차이를 빠르게 이해시키는 방식으로 씁니다.",
    "실수방지형": "탈락, 부적격, 비용 누락 같은 실수 포인트를 전면에 배치합니다.",
    "체크리스트형": "실행 순서와 점검 항목을 짧고 명확하게 끊어서 씁니다.",
    "사례형": "가상의 독자 사례를 앞세워 판단 흐름을 따라가게 씁니다.",
    "FAQ형": "자주 묻는 질문을 연속 배치해 검색 체류시간을 높이는 방식으로 씁니다.",
}

FAMILY_PRESETS = {
    "기초": {
        "audiences": ["청약초보", "청년 1인 가구", "사회초년생", "무주택 실수요자", "30대 맞벌이", "예비 신혼부부"],
        "intents": ["조건정리", "가능여부", "비교", "실수방지", "체크리스트"],
        "scenarios": ["처음 준비할 때", "세대분리 전", "통장만 있을 때", "기준이 헷갈릴 때", "청약 처음 넣기 전", "무주택 유지 중일 때"],
        "secondaries": ["1순위", "예치금", "세대주", "무주택", "청약홈", "납입횟수", "부양가족수"],
        "priority": 100,
    },
    "특공": {
        "audiences": ["신혼부부", "예비부부", "생애최초 준비자", "다자녀 가구", "노부모 부양 세대", "신생아 특공 준비자"],
        "intents": ["조건정리", "가능여부", "비교", "실수방지", "사례"],
        "scenarios": ["소득이 애매할 때", "자녀 수가 기준선일 때", "배우자 이력이 있을 때", "혼인 시점이 걸릴 때", "출산 직후", "특공끼리 비교할 때"],
        "secondaries": ["소득기준", "자산기준", "부적격", "신혼희망타운", "우선공급", "가구원수"],
        "priority": 95,
    },
    "일반공급": {
        "audiences": ["무주택 실수요자", "저가점 청약자", "고가점 청약자", "1주택 갈아타기 준비자", "가점 낮은 청약자"],
        "intents": ["조건정리", "가능여부", "비교", "전략", "실수방지"],
        "scenarios": ["가점이 낮을 때", "추첨제 물량을 볼 때", "규제지역 청약 전", "당해가 애매할 때", "예비당첨 노릴 때", "커트라인이 걱정될 때"],
        "secondaries": ["가점제", "추첨제", "당해", "예비당첨", "커트라인", "당첨확률"],
        "priority": 92,
    },
    "규제": {
        "audiences": ["무주택 실수요자", "1주택 갈아타기 준비자", "분양권 매수 검토자", "청약초보", "실거주 예정자"],
        "intents": ["조건정리", "가능여부", "비교", "실수방지"],
        "scenarios": ["규제지역일 때", "당첨 이후", "매수 전에", "전매 계획이 있을 때", "입주 직전", "세대분리 직후"],
        "secondaries": ["재당첨 제한", "전매제한", "거주의무", "부적격", "주택수", "규제지역"],
        "priority": 90,
    },
    "자금": {
        "audiences": ["무주택 실수요자", "30대 맞벌이", "신혼부부", "저가점 청약자", "현금이 빠듯한 실수요자"],
        "intents": ["계산", "조건정리", "실수방지", "체크리스트", "사례"],
        "scenarios": ["계약금이 빠듯할 때", "중도금 대출이 필요할 때", "잔금이 걱정될 때", "월 상환액을 따질 때", "입주가 겹칠 때", "옵션비가 부담될 때"],
        "secondaries": ["계약금", "중도금", "잔금", "대출", "취득세", "옵션비", "현금흐름"],
        "priority": 93,
    },
    "대안": {
        "audiences": ["저가점 청약자", "무주택 실수요자", "1주택 갈아타기 준비자", "투자 겸 실거주 검토자", "당장 입주 필요한 수요자"],
        "intents": ["가능여부", "비교", "전략", "실수방지", "사례"],
        "scenarios": ["당첨이 어려울 때", "청약통장이 약할 때", "당장 입주가 필요할 때", "매수와 청약 사이에서 고민할 때", "무순위만 기다릴 때", "미분양 검토할 때"],
        "secondaries": ["무순위", "잔여세대", "분양권", "입주권", "미분양", "줍줍"],
        "priority": 88,
    },
    "실무": {
        "audiences": ["청약초보", "무주택 실수요자", "신혼부부", "사회초년생", "예비당첨자"],
        "intents": ["체크리스트", "실수방지", "조건정리", "FAQ"],
        "scenarios": ["청약 직전", "청약홈 접속 전", "서류 준비 전", "당첨 직후", "계약 직전", "예비당첨 연락 전"],
        "secondaries": ["입주자모집공고", "청약홈", "서류", "체크리스트", "당첨 후 절차", "기준일"],
        "priority": 91,
    },
    "세금": {
        "audiences": ["1주택 갈아타기 준비자", "무주택 실수요자", "분양권 매수 검토자", "실거주 예정자"],
        "intents": ["조건정리", "비교", "실수방지", "FAQ"],
        "scenarios": ["매수 전에", "입주 직전", "갈아타기할 때", "일시적 2주택이 될 때"],
        "secondaries": ["취득세", "양도세", "보유세", "일시적 2주택", "비과세"],
        "priority": 87,
    },
    "입지": {
        "audiences": ["실거주 예정자", "신혼부부", "30대 맞벌이", "투자 겸 실거주 검토자"],
        "intents": ["비교", "전략", "체크리스트", "사례"],
        "scenarios": ["실거주로 볼 때", "투자와 비교할 때", "입주 전 현장 볼 때", "교통이 애매할 때"],
        "secondaries": ["역세권", "학군", "생활권", "직주근접", "입지"],
        "priority": 80,
    },
    "당첨후": {
        "audiences": ["본당첨자", "예비당첨자", "무주택 실수요자", "1주택 갈아타기 준비자"],
        "intents": ["체크리스트", "실수방지", "조건정리", "FAQ"],
        "scenarios": ["당첨 직후", "계약 직전", "서류 보완 전", "포기 고민할 때"],
        "secondaries": ["계약 포기", "예비당첨", "서류 보완", "계약 일정", "부적격"],
        "priority": 89,
    },
    "공공분양": {
        "audiences": ["무주택 실수요자", "신혼부부", "청년 1인 가구", "생애최초 준비자"],
        "intents": ["조건정리", "비교", "가능여부", "실수방지"],
        "scenarios": ["공공분양 검토할 때", "민간분양과 비교할 때", "소득 기준이 애매할 때", "사전청약 이후 볼 때"],
        "secondaries": ["공공분양", "민간분양", "사전청약", "소득기준", "공급유형"],
        "priority": 86,
    },
    "민간분양": {
        "audiences": ["무주택 실수요자", "1주택 갈아타기 준비자", "30대 맞벌이", "실거주 예정자"],
        "intents": ["조건정리", "비교", "전략", "사례"],
        "scenarios": ["민간분양 볼 때", "규제지역에서 볼 때", "가점이 낮을 때", "실거주 목적으로 볼 때"],
        "secondaries": ["민간분양", "공공분양", "가점제", "추첨제", "입주자모집공고"],
        "priority": 85,
    },
    "임대": {
        "audiences": ["청년 1인 가구", "신혼부부", "무주택 실수요자", "사회초년생"],
        "intents": ["조건정리", "가능여부", "비교", "체크리스트"],
        "scenarios": ["공공임대 볼 때", "행복주택과 비교할 때", "소득기준이 애매할 때", "전세 대신 검토할 때"],
        "secondaries": ["공공임대", "행복주택", "국민임대", "매입임대", "소득기준"],
        "priority": 82,
    },
    "갈아타기": {
        "audiences": ["1주택 갈아타기 준비자", "실거주 예정자", "기존주택 처분 예정자", "전세 만기 예정자"],
        "intents": ["전략", "실수방지", "체크리스트", "사례"],
        "scenarios": ["기존 집 매도 전", "전세 만기 직전", "입주 일정이 겹칠 때", "자금이 묶일 때"],
        "secondaries": ["기존주택 처분", "전세 만기", "이사 일정", "거주의무", "잔금"],
        "priority": 84,
    },
    "확률분석": {
        "audiences": ["저가점 청약자", "고가점 청약자", "무주택 실수요자", "예비당첨 노리는 청약자"],
        "intents": ["전략", "비교", "계산", "FAQ"],
        "scenarios": ["경쟁률이 높을 때", "커트라인이 애매할 때", "예비당첨 노릴 때", "가점이 낮을 때"],
        "secondaries": ["당첨확률", "경쟁률", "가점", "예비당첨", "커트라인"],
        "priority": 83,
    },
}


@dataclass(frozen=True)
class TopicBlueprint:
    family: str
    primary_keyword: str
    secondary_keywords: tuple[str, ...] = ()
    audiences: tuple[str, ...] = ()
    intents: tuple[str, ...] = ()
    scenarios: tuple[str, ...] = ()
    comparison_keyword: str | None = None


TOPIC_BLUEPRINTS = [
    TopicBlueprint("기초", "청약통장", comparison_keyword="청년주택드림청약통장"),
    TopicBlueprint("기초", "무주택 기준", comparison_keyword="주택 수 판정"),
    TopicBlueprint("기초", "세대주 세대원", comparison_keyword="세대분리"),
    TopicBlueprint("기초", "1순위 조건", comparison_keyword="2순위"),
    TopicBlueprint("기초", "예치금", comparison_keyword="납입횟수"),
    TopicBlueprint("기초", "납입횟수", comparison_keyword="예치금"),
    TopicBlueprint("기초", "부양가족수", comparison_keyword="무주택기간"),
    TopicBlueprint("기초", "무주택기간", comparison_keyword="부양가족수"),
    TopicBlueprint("기초", "청약가점", comparison_keyword="추첨제"),
    TopicBlueprint("기초", "세대분리", comparison_keyword="세대주 세대원"),
    TopicBlueprint("실무", "입주자모집공고", comparison_keyword="청약홈"),
    TopicBlueprint("실무", "청약홈", comparison_keyword="입주자모집공고"),
    TopicBlueprint("실무", "서류 준비", comparison_keyword="기준일"),
    TopicBlueprint("실무", "기준일", comparison_keyword="서류 준비"),
    TopicBlueprint("실무", "예비당첨", comparison_keyword="본당첨"),
    TopicBlueprint("실무", "당첨 후 절차", comparison_keyword="계약 일정"),
    TopicBlueprint("특공", "신혼부부 특별공급", comparison_keyword="생애최초 특별공급"),
    TopicBlueprint("특공", "생애최초 특별공급", comparison_keyword="신혼부부 특별공급"),
    TopicBlueprint("특공", "다자녀 특별공급", comparison_keyword="노부모 부양 특별공급"),
    TopicBlueprint("특공", "노부모 부양 특별공급", comparison_keyword="다자녀 특별공급"),
    TopicBlueprint("특공", "기관추천 특별공급", comparison_keyword="일반공급"),
    TopicBlueprint("특공", "신생아 특별공급", comparison_keyword="신혼부부 특별공급"),
    TopicBlueprint("특공", "신혼희망타운", comparison_keyword="공공분양"),
    TopicBlueprint("특공", "특별공급 부적격", comparison_keyword="일반공급"),
    TopicBlueprint("일반공급", "가점제", comparison_keyword="추첨제"),
    TopicBlueprint("일반공급", "추첨제", comparison_keyword="가점제"),
    TopicBlueprint("일반공급", "당해", comparison_keyword="기타지역"),
    TopicBlueprint("일반공급", "예비당첨", comparison_keyword="본당첨"),
    TopicBlueprint("일반공급", "커트라인", comparison_keyword="당첨확률"),
    TopicBlueprint("일반공급", "당첨확률", comparison_keyword="커트라인"),
    TopicBlueprint("규제", "재당첨 제한", comparison_keyword="특별공급 1회 제한"),
    TopicBlueprint("규제", "전매제한", comparison_keyword="거주의무"),
    TopicBlueprint("규제", "거주의무", comparison_keyword="전매제한"),
    TopicBlueprint("규제", "부적격 당첨", comparison_keyword="중복당첨"),
    TopicBlueprint("규제", "중복당첨", comparison_keyword="부적격 당첨"),
    TopicBlueprint("규제", "주택 수 판정", comparison_keyword="무주택 기준"),
    TopicBlueprint("자금", "계약금 중도금 잔금", comparison_keyword="중도금 대출"),
    TopicBlueprint("자금", "중도금 대출", comparison_keyword="잔금 대출"),
    TopicBlueprint("자금", "잔금 대출", comparison_keyword="중도금 대출"),
    TopicBlueprint("자금", "취득세", comparison_keyword="양도세"),
    TopicBlueprint("자금", "월 상환액", comparison_keyword="자기자본"),
    TopicBlueprint("자금", "옵션비", comparison_keyword="발코니 확장"),
    TopicBlueprint("자금", "발코니 확장", comparison_keyword="옵션비"),
    TopicBlueprint("자금", "현금흐름", comparison_keyword="월 상환액"),
    TopicBlueprint("대안", "무순위 청약", comparison_keyword="잔여세대"),
    TopicBlueprint("대안", "잔여세대", comparison_keyword="무순위 청약"),
    TopicBlueprint("대안", "분양권", comparison_keyword="입주권"),
    TopicBlueprint("대안", "입주권", comparison_keyword="분양권"),
    TopicBlueprint("대안", "미분양", comparison_keyword="무순위 청약"),
    TopicBlueprint("대안", "줍줍", comparison_keyword="무순위 청약"),
    TopicBlueprint("세금", "취득세", comparison_keyword="보유세"),
    TopicBlueprint("세금", "양도세", comparison_keyword="취득세"),
    TopicBlueprint("세금", "보유세", comparison_keyword="취득세"),
    TopicBlueprint("세금", "일시적 2주택", comparison_keyword="비과세"),
    TopicBlueprint("세금", "비과세", comparison_keyword="일시적 2주택"),
    TopicBlueprint("입지", "역세권", comparison_keyword="직주근접"),
    TopicBlueprint("입지", "학군", comparison_keyword="생활권"),
    TopicBlueprint("입지", "생활권", comparison_keyword="학군"),
    TopicBlueprint("입지", "직주근접", comparison_keyword="역세권"),
    TopicBlueprint("당첨후", "계약 포기", comparison_keyword="재당첨 제한"),
    TopicBlueprint("당첨후", "서류 보완", comparison_keyword="부적격 당첨"),
    TopicBlueprint("당첨후", "계약 일정", comparison_keyword="당첨 후 절차"),
    TopicBlueprint("당첨후", "예비당첨 연락", comparison_keyword="예비당첨"),
    TopicBlueprint("기초", "청약 가능 지역", comparison_keyword="당해 기타지역"),
    TopicBlueprint("기초", "세대원 기준", comparison_keyword="세대주 기준"),
    TopicBlueprint("기초", "청약통장 해지", comparison_keyword="당첨 후 절차"),
    TopicBlueprint("특공", "다자녀 기준", comparison_keyword="노부모 부양 기준"),
    TopicBlueprint("특공", "혼인기간", comparison_keyword="소득기준"),
    TopicBlueprint("특공", "가구원수", comparison_keyword="소득기준"),
    TopicBlueprint("일반공급", "해당지역 우선", comparison_keyword="기타지역"),
    TopicBlueprint("일반공급", "청약 경쟁률", comparison_keyword="가점 커트라인"),
    TopicBlueprint("일반공급", "예비당첨 순번", comparison_keyword="본당첨"),
    TopicBlueprint("규제", "규제지역", comparison_keyword="비규제지역"),
    TopicBlueprint("규제", "비규제지역", comparison_keyword="규제지역"),
    TopicBlueprint("규제", "주택 수", comparison_keyword="무주택 기준"),
    TopicBlueprint("자금", "자기자본", comparison_keyword="월 상환액"),
    TopicBlueprint("자금", "잔금 부족", comparison_keyword="중도금 대출"),
    TopicBlueprint("자금", "이사비", comparison_keyword="옵션비"),
    TopicBlueprint("세금", "종합부동산세", comparison_keyword="재산세"),
    TopicBlueprint("세금", "재산세", comparison_keyword="종합부동산세"),
    TopicBlueprint("세금", "양도세 비과세", comparison_keyword="일시적 2주택"),
    TopicBlueprint("입지", "역세권 실거주", comparison_keyword="직주근접"),
    TopicBlueprint("입지", "학군 실거주", comparison_keyword="생활권"),
    TopicBlueprint("입지", "생활 인프라", comparison_keyword="교통"),
    TopicBlueprint("입지", "직주근접", comparison_keyword="생활 인프라"),
    TopicBlueprint("실무", "청약홈 신청내역", comparison_keyword="입주자모집공고"),
    TopicBlueprint("실무", "주민등록등본 초본", comparison_keyword="가족관계증명서"),
    TopicBlueprint("실무", "서류 기준일", comparison_keyword="공고일"),
    TopicBlueprint("당첨후", "당첨 후 서류", comparison_keyword="서류 보완"),
    TopicBlueprint("당첨후", "계약금 납부일", comparison_keyword="계약 일정"),
    TopicBlueprint("당첨후", "당첨 취소", comparison_keyword="계약 포기"),
    TopicBlueprint("공공분양", "공공분양", comparison_keyword="민간분양"),
    TopicBlueprint("공공분양", "사전청약", comparison_keyword="본청약"),
    TopicBlueprint("공공분양", "공공분양 소득기준", comparison_keyword="민간분양"),
    TopicBlueprint("민간분양", "민간분양", comparison_keyword="공공분양"),
    TopicBlueprint("민간분양", "분양가상한제", comparison_keyword="민간분양"),
    TopicBlueprint("민간분양", "민영주택", comparison_keyword="국민주택"),
    TopicBlueprint("임대", "공공임대", comparison_keyword="행복주택"),
    TopicBlueprint("임대", "행복주택", comparison_keyword="국민임대"),
    TopicBlueprint("임대", "국민임대", comparison_keyword="공공임대"),
    TopicBlueprint("임대", "매입임대", comparison_keyword="전세임대"),
    TopicBlueprint("임대", "전세임대", comparison_keyword="매입임대"),
    TopicBlueprint("갈아타기", "기존주택 처분", comparison_keyword="거주의무"),
    TopicBlueprint("갈아타기", "전세 만기", comparison_keyword="이사 일정"),
    TopicBlueprint("갈아타기", "이사 일정", comparison_keyword="잔금 일정"),
    TopicBlueprint("갈아타기", "잔금 일정", comparison_keyword="기존주택 처분"),
    TopicBlueprint("확률분석", "당첨확률", comparison_keyword="경쟁률"),
    TopicBlueprint("확률분석", "경쟁률", comparison_keyword="커트라인"),
    TopicBlueprint("확률분석", "커트라인", comparison_keyword="예비당첨"),
    TopicBlueprint("확률분석", "예비당첨 확률", comparison_keyword="본당첨"),
]
